version: '3.6'

services:
  api-html2img:
    hostname: api_html2img
    build: .
    restart: unless-stopped
    # command: ./gochro -host 0.0.0.0:80 -disable-sandbox
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=traefik_proxy
#       - traefik.http.services.api-html2img.loadbalancer.server.port=80
# #       - traefik.http.routers.api-html2img-pub.middlewares=sso
# #       - traefik.http.routers.api-html2img-pub.tls=true
# #       - traefik.http.routers.api-html2img-pub.tls.certResolver=letsencrypt
# #       - traefik.http.routers.api-html2img-pub.service=cronicle
# #
#       - traefik.http.routers.api-html2img.rule=Host(`api.vps.${DOMAIN_NAME}`) && PathPrefix(`/html2img`)
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
